language: php

php:
  - '7.1'

sudo: false

before_script:
- cp .env.test .env
- composer self-update
- composer install --prefer-source --no-interaction
- php artisan key:generate

before_install:
- mysql -e 'CREATE DATABASE indiehd_test;'
- mysql -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';"
- mysql --user=root -e "GRANT ALL PRIVILEGES ON indiehd_test.* TO 'homestead'@'%' WITH GRANT OPTION;"
- mysql --user=root -e 'FLUSH PRIVILEGES;'

services:
- mysql

script:
  - vendor/bin/phpunit tests

notifications:
  email:
#    recipients:
#      - gtaylor@electricwerks.com
#    on_success: always
#    on_failure: always
    on_failure: change